set(UNRAR_FILES
    unrar/filestr.cpp
    unrar/recvol.cpp
    unrar/rs.cpp
    unrar/scantree.cpp
    unrar/qopen.cpp
    unrar/rar.cpp
    unrar/strlist.cpp
    unrar/strfn.cpp
    unrar/pathfn.cpp
    unrar/smallfn.cpp
    unrar/global.cpp
    unrar/file.cpp
    unrar/filefn.cpp
    unrar/filcreat.cpp
    unrar/archive.cpp
    unrar/arcread.cpp
    unrar/unicode.cpp
    unrar/system.cpp
    unrar/crypt.cpp
    unrar/crc.cpp
    unrar/rawread.cpp
    unrar/encname.cpp
    unrar/resource.cpp
    unrar/match.cpp
    unrar/timefn.cpp
    unrar/rdwrfn.cpp
    unrar/consio.cpp
    unrar/options.cpp
    unrar/errhnd.cpp
    unrar/rarvm.cpp
    unrar/secpassword.cpp
    unrar/rijndael.cpp
    unrar/getbits.cpp
    unrar/sha1.cpp
    unrar/sha256.cpp
    unrar/blake2s.cpp
    unrar/hash.cpp
    unrar/extinfo.cpp
    unrar/extract.cpp
    unrar/volume.cpp
    unrar/list.cpp
    unrar/find.cpp
    unrar/unpack.cpp
    unrar/headers.cpp
    unrar/threadpool.cpp
    unrar/rs16.cpp
    unrar/cmddata.cpp
    unrar/ui.cpp
)